Add image save button
nagata-yoshiteru/ppm-pgm-viewer-for-vscode pull request #13
Opened 2021-11-28 03:41 UTC by szk18

Hi, I've added a save image button. 
I had used screenshots to save images, but it didn't save a image cleanly.
So, I implemented saving image feature using `HTMLCanvasElement.toDataURL()` ([document](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)) .
![image](https://user-images.githubusercontent.com/39793156/143728184-64ffee90-3e9d-4beb-a9f6-c7948f458586.png)

I would like to discuss about size of the image to be saved.
In the current implementation.  the size of the saved image depends on the zoom level(canvas size).
For example. an image with a zoom level of 200% will be larger than an image with a zoom level of 100%.
Should we keep this implementation or fix the size of the image to be saved?

I tested the feature in Windows, MacOS, and wsl, and It worked.
Please review this pull request when you have time. Thanks!

### Changes
- change class name 'resetButton' to 'wideButton'
- add `saveImg()` function to save canvas image

2021-11-28 03:44 UTC, szk18 commented
If you don't think  that you need this feature. please close this PR.

2021-11-28 03:56 UTC, BenWeisz commented
Hi! I'll take a look at this tomorrow, I'm sort of swamped with school work right now

2021-11-28 14:22 UTC, nagata-yoshiteru commented
@szk18 
Hello!
Thanks for your nice feature!
It also works in my environment and your code looks fine!

I think an image should be saved with a zoom level of 100% because most image editor saves an image with a 1:1 ratio.

I also think that it would be better to 
- change a button label ( currently `Save Image` ) into `Save as PNG` if we only support PNG.
- set a default file name as same as an original image name.
I would like to discuss the above points.

Thanks!

2021-11-28 14:53 UTC, szk18 commented
@nagata-yoshiteru 
Thank you for your review! I'm glad to hear it worked well😁.

> I think an image should be saved with a zoom level of 100% because most image editor saves an image with a 1:1 ratio.

Thanks for your opinion. I will try to implement it that way.

> change a button label ( currently Save Image ) into Save as PNG if we only support PNG.

In the current implementation, the image will be saved in png format.
we can support other formats(ex. jpeg) by using `type` parameter.
But I think that we should support only PNG format to keep the functionality simple.

> set a default file name as same as an original image name.

I think it would be a good idea 👍

2021-11-29 00:35 UTC, BenWeisz commented
Yup, I can definitely see this being useful on platforms where .pgm has no native image viewer support for it. (For example windows to the best of my knowledge) 

On the question of the image scale I definitely agree that it should be in saved in the 100% zoom mode.

2021-11-29 01:13 UTC, szk18 commented
@BenWeisz 
Thanks! I think this feature is useful when user want to share ppm images on platform that don't support ppm(such as twitter).

> On the question of the image scale I definitely agree that it should be in saved in the 100% zoom mode.

Thanks for your answer 👍

2021-11-29 04:48 UTC, szk18 commented on src/webview.ts
> +            saveLink.download = "image.png";
Thanks, I'm implementing it now!

2021-11-29 05:15 UTC, szk18 commented
Hi! I've completed the fix. Please review the changes when you have a time.

I've done the implementation again related in the `file path`.
This time, I used `path` module of `node.js`. 
 I tested in my windows10 environment, but there may be some bugs. 
@nagata-yoshiteru  
Can you test my code in your windows environment?

2021-11-29 05:23 UTC, BenWeisz requested changes
Two small things

2021-11-29 05:23 UTC, BenWeisz commented on src/webview.ts
> +import * as path from 'path';
```suggestion
import * as path from "path";
```

Small thing for consistency with the other imports

2021-11-29 05:23 UTC, BenWeisz commented on src/webview.ts
> +            showImg(scale); // restore zoom level
Does this only restore the zoom for the export image or does it also resize the entire window? Im not sure if this is possible but it would be cool if there were a way to not reset the zoom and still save the file in 100%

2021-11-29 05:28 UTC, szk18 commented on src/webview.ts
> +import * as path from 'path';
oh, sorry.

2021-11-29 05:49 UTC, szk18 commented on src/webview.ts
> +            showImg(scale); // restore zoom level
This implementation, it resize the displayed canvas.
I thought so too, but `showImg`  function is specified `canvas`.

https://github.com/nagata-yoshiteru/ppm-pgm-viewer-for-vscode/blob/e211531b18b60648e3fc4229f9bf5c0df367f932/src/webview.ts#L69

we may be able to accomplish it by extracting scale process from `showImg`,

2021-11-29 15:41 UTC, szk18 commented on src/webview.ts
> +            showImg(scale); // restore zoom level
I've tried to implement it.  https://github.com/nagata-yoshiteru/ppm-pgm-viewer-for-vscode/pull/13/commits/58ddef637498e168905fa62efc78235d041e5707

1. extract the canvas scaling process to `scaleCanvas`
2. create new canvas for save using `cloneNode()` in `saveImg`

2021-11-29 17:11 UTC, nagata-yoshiteru commented
@szk18 

> Can you test my code in your windows environment?

I tested your latest code and everything worked well!
Thanks for your hard work!

2021-11-30 01:18 UTC, szk18 commented
@nagata-yoshiteru 
Thank you for testing in your environment! 

@BenWeisz 
Can you review my latest code, when you have a time? (https://github.com/nagata-yoshiteru/ppm-pgm-viewer-for-vscode/pull/13#discussion_r758485535)

2021-12-02 20:14 UTC, BenWeisz commented
Hey @szk18 I havent had the chance to test out the code but the code looks good in general. I think its good for now but I can take a more in depth look in a few weeks

2021-12-03 00:16 UTC, szk18 commented
Hi, @BenWeisz. 
Ok, this PR is a new feature addition, so we don't need to rush. 
I'm looking forward to your review and merging this PR!

2021-12-08 04:44 UTC, BenWeisz commented on src/webview.ts
> +            showImg(scale); // restore zoom level
Hey, it looks to be fine on my MacOS laptop, so I think this should work. If we have any performance issues with `cloneNode` we can always revisit it later. Thanks for implementing this!

2021-12-08 04:44 UTC, BenWeisz commented
@szk18 @nagata-yoshiteru This should be ready to merge

2021-12-08 04:47 UTC, nagata-yoshiteru commented
Ok, I will merge this PR and prepare a new release!

2021-12-08 04:47 UTC, merged

2021-12-08 08:22 UTC, szk18 commented on src/webview.ts
> +            showImg(scale); // restore zoom level
> If we have any performance issues with cloneNode we can always revisit it later. Thanks for implementing this!

OK! Thank you for your review!

2021-12-08 08:29 UTC, szk18 commented
Hi! Thank you very much for all the reviews! I'm very happy that my proposal was accepted😁.