Add panel color configuration
nagata-yoshiteru/ppm-pgm-viewer-for-vscode pull request #6
Opened 2021-06-30 15:53 UTC by nagata-yoshiteru

## Description

Add panel color configuration so that users can customize it by their preference.

### Changes
- Add extension configuration
- Change panel color based on the config

2021-06-30 15:59 UTC, nagata-yoshiteru commented
Hi, @BenWeisz!
I've added the panel color customization feature. Let me know what you think!
Thanks.

2021-06-30 18:23 UTC, weiszben requested changes

2021-06-30 18:23 UTC, weiszben commented on src/webview.ts
>  ): string => {
I think the code would be a bit cleaner if we move the css object into the function and then insert the colors into the class strings

2021-06-30 18:23 UTC, weiszben commented on src/webview.ts
> +            <div onclick="scale = scale / 2; showImg(scale);" style="${styles.sizingButton} background-color: ${btnColor};">-</div>
By doing the above, we could remove the duplicate `background-color` tag here

2021-07-02 08:46 UTC, nagata-yoshiteru commented on src/webview.ts
>  ): string => {
Ok, I'll try to do that!

2021-07-02 09:31 UTC, nagata-yoshiteru reviewed
@BenWeisz 
I refactored the code based on your suggestion!
Thanks!

2021-07-08 04:02 UTC, BenWeisz approved these changes

2021-07-09 04:36 UTC, merged